name: Go
on:
  push:
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.15
      uses: actions/setup-go@v1
      with:
        go-version: 1.15
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@master

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Build
      run: |
        GITVER=$(git describe --tags || git rev-parse --short HEAD)
        GOOS=linux GOARCH=amd64 go build -ldflags="-s -w -X main.MAINVER=${GITVER}" -v -o gray_amd64_linux .
        GOOS=linux GOARCH=arm64 go build -ldflags="-s -w -X main.MAINVER=${GITVER}" -v -o gray_arm64_linux .
        GOOS=linux GOARCH=arm GOARM=7 go build -ldflags="-s -w -X main.MAINVER=${GITVER}" -v -o gray_armv7_linux .
        GOOS=windows GOARCH=amd64 go build -ldflags="-s -w -X main.MAINVER=${GITVER}" -v -o gray_amd64_windows.exe .
        tar czf gray_amd64_linux.tar.gz gray_amd64_linux
        tar czf gray_arm64_linux.tar.gz gray_arm64_linux
        tar czf gray_armv7_linux.tar.gz gray_armv7_linux
        zip gray_amd64_windows.zip gray_amd64_windows.exe

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          gray_amd64_linux.tar.gz 
          gray_arm64_linux.tar.gz 
          gray_armv7_linux.tar.gz 
          gray_amd64_windows.zip 
      env:
        GITHUB_TOKEN: ${{ secrets.X_GITHUB_TOKEN }}

